services:
  - type: web
    name: mourning-well
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn mourning_well.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: WEB_CONCURRENCY
        value: "4"
