# Generated by Django 6.1 on 2026-08-12 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The reflection question or prompt.')),
                ('stage', models.CharField(choices=[('early', 'Early days'), ('processing', 'Processing'), ('remembering', 'Remembering'), ('moving_forward', 'Moving forward')], default='processing', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['stage', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('hotline', 'Hotline'), ('article', 'Article'), ('book', 'Book'), ('organization', 'Organization')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['kind', 'title'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='support.prompt')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-created'],
            },
        ),
    ]
